// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Blog = Collections['blog']['schema']['_output']
export declare const blog: Blog[]

export type EasyAiTechnology = Collections['easyAiTechnology']['schema']['_output']
export declare const easyAiTechnology: EasyAiTechnology[]

export type Seo = Collections['seo']['schema']['_output']
export declare const seo: Seo[]
